### ISSUE TITLE
Check that Ships are within the Game Board Bounds

### ISSUE THREAD

**Issue by logan-kling** [OSU-CS361-W17/group5_project1#12]
Write a function to check currently requested ship placement coordinates are within the bounds of the game board. The function takes in coordinates, ornamentation, length. The game state is not needed as the game board size is static.

**Comment by jackson-wells** [comment]
Already wrote this function

**Comment by logan-kling** [comment]
Hey Jackson, I noticed this function only returns a 1 or a 0. Given that, you should change its return type to a Bool.
